# Setup
title:               Taylor Jones
description:         'Network and Systems Engineer Focused on Automation'
color-scheme: dark
url:                 http://taylorjones.engineer
email: me@taylorjones.engineer
logo: /assets/img/logo.png


platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/t-jonesy
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/taylrjones/
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/files/vaibhav_vikas_resume.pdf

# About/contact
author:
  name:              Taylor Jones
  url:               https://taylorjones.engineer
  email:             me@taylorjones.engineer

# Gems
plugins:
  - jekyll-remote-theme
#theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
